Repository fingerthief/minimal-chat, pull requests merged in 2024-05, with the labels that each got.

#68 Redesigned the messages interface to be more clean and minimal
  .firebase/hosting.ZGlzdA.cache
  README.md
  src/components/chat-input.vue
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/views/ChatLayout.vue
Labels: enhancement

#69 Added the ability to download, cache, load and run certain llm models completely locallyi in the users browser
  README.md
  package-lock.json
  package.json
  src/components/chat-header.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/web-llm-access.js
  src/views/ChatLayout.vue
Labels: enhancement

#76 Feature/add ability to set system prompt
  README.md
  src/components/InputField.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/claude-api-access.js
  src/views/ChatLayout.vue
Labels: enhancement

#77 Feature/upload files to import text into conversation
  .firebase/hosting.ZGlzdA.cache
  src/components/chat-input.vue
  src/components/conversations-dialog.vue
  src/views/ChatLayout.vue
Labels: enhancement

#85 Added Dynamic Rendering of Messages List
  README.md
  package-lock.json
  package.json
  src/components/message-item.vue
  src/components/settings-dialog.vue
Labels: enhancement

#88 Updates to fix bug with scrolling to bottom logic and the new dynamically rendered messages list.
  src/components/message-item.vue
  src/views/ChatLayout.vue
Labels: bug

#87 Enhance Local LLM Stream Response Parsing
  src/libs/utils.js
Labels: enhancement

#90 Updated parseOpenAiFormatResponseChunk to strip OpenRouter ending text
  src/libs/utils.js
Labels: bug, enhancement

#93 Implement collapsible config-sections in settings-dialog
  src/components/settings-dialog.vue
Labels: enhancement

#94 Fixed Dynamic Message Rendering and Scroll to Bottom Issue
  CHANGELOG.md
  README.md
  package.json
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/views/ChatLayout.vue
Labels: bug, enhancement

#96 Added Additional Local Browser Model Options
  CHANGELOG.md
  package.json
  src/components/settings-dialog.vue
Labels: enhancement

#102 Enhance UI Structure of message-item.vue with Header Sections and Improved Styling
  src/components/message-item.vue
Labels: enhancement

#103 Fix Config Section Not Loading on Startup
  Dockerfile
  package.json
  src/libs/utils.js
  src/views/ChatLayout.vue
Labels: bug

#104 Add a max_tokens limit to the title generation
  src/libs/open-ai-api-standard-access.js
Labels: enhancement

#105 Conversation Storage/Processing Logic Overhaul
  .firebase/hosting.ZGlzdA.cache
  CHANGELOG.md
  README.md
  package.json
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/conversations-management.js
  src/views/ChatLayout.vue
Labels: enhancement

#107 Add import/export functionality to settings-dialog
  src/components/settings-dialog.vue
  src/libs/settings-utils.js
Labels: enhancement

#112 Save Multiple System Prompts
  .firebase/hosting.ZGlzdA.cache
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/settings-utils.js
  src/views/ChatLayout.vue
Labels: enhancement

#113 [Feature] Save Multiple Custom Endpoint Configs
  src/components/settings-dialog.vue
Labels: enhancement

#115 [Enhancement] Site Design Consistency Improvements and Styles Refactor
  README.md
  package.json
  src/components/chat-header.vue
  src/components/chat-input.vue
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/views/ChatLayout.vue
Labels: enhancement

#116 Restructured Message Text Streaming UI Updating Process
  src/components/message-item.vue
  src/views/ChatLayout.vue
Labels: enhancement

#119 [Maintainability] Conversation Management Library Expansion and Message Sending Library Creation
  .firebase/hosting.ZGlzdA.cache
  .github/workflows/pull-requests-generation
  .github/workflows/pull-requests-generation.yml
  .prettierrc.json
  CHANGELOG.md
  README.md
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/assets/base.css
  src/assets/main.css
  src/components/InputField.vue
  src/components/__tests__/HelloWorld.spec.js
  src/components/chat-header.vue
  src/components/chat-input.vue
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/claude-api-access.js
  src/libs/conversations-management.js
  src/libs/gpt-api-access.js
  src/libs/image-analysis.js
  src/libs/message-sending.js
  src/libs/open-ai-api-standard-access.js
  src/libs/settings-utils.js
  src/libs/utils.js
  src/libs/web-llm-access.js
  src/main.js
  src/router/index.js
  src/views/ChatLayout.vue
  vite.config.js
Labels: enhancement

#121 Further Refactor Chatlayout and Expand Libraries
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .prettierrc.json
  CHANGELOG.md
  package.json
  src/App.vue
  src/assets/base.css
  src/assets/main.css
  src/assets/manifest.webmanifest
  src/components/InputField.vue
  src/components/ToolTip.vue
  src/components/__tests__/HelloWorld.spec.js
  src/components/chat-header.vue
  src/components/chat-input.vue
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/claude-api-access.js
  src/libs/conversations-management.js
  src/libs/file-processing.js
  src/libs/gpt-api-access.js
  src/libs/image-analysis.js
  src/libs/message-processing.js
  src/libs/message-sending.js
  src/libs/open-ai-api-standard-access.js
  src/libs/settings-utils.js
  src/libs/utils.js
  src/libs/web-llm-access.js
  src/router/index.js
  src/views/ChatLayout.vue
Labels: enhancement

#122 Added Tree Shaking to Build Process
  package-lock.json
  package.json
  src/libs/conversations-management.js
  src/views/ChatLayout.vue
  vite.config.js
Labels: enhancement

#125 ChatLayout Refactor and Expanding Library Files Suite
  .firebase/hosting.ZGlzdA.cache
  .github/workflows/pull-requests-generation.yml
  CHANGELOG.md
  README.md
  package.json
  src/components/InputField.vue
  src/components/chat-header.vue
  src/components/chat-input.vue
  src/components/conversations-dialog.vue
  src/components/message-item.vue
  src/components/settings-dialog.vue
  src/libs/api-access/claude-api-access.js
  src/libs/api-access/gpt-api-access.js
  src/libs/api-access/open-ai-api-standard-access.js
  src/libs/api-access/web-llm-access.js
  src/libs/conversation-management/conversations-management.js
  src/libs/conversation-management/message-processing.js
  src/libs/conversation-management/useConversations.js
  src/libs/file-processing/file-processing.js
  src/libs/file-processing/image-analysis.js
  src/libs/state-management/state.js
  src/libs/state-management/watchers.js
  src/libs/utils/constants.js
  src/libs/utils/general-utils.js
  src/libs/utils/settings-utils.js
  src/views/ChatLayout.vue
Labels: enhancement

#126 Fix Issues With Message Regens and Browser Model Message Generation
  .firebase/hosting.ZGlzdA.cache
  index.html
  src/components/ChatHeader.vue
  src/components/ChatInput.vue
  src/components/ConversationsDialog.vue
  src/components/MessageItem.vue
  src/components/SettingsDialog.vue
  src/libs/api-access/claude-api-access.js
  src/libs/api-access/gpt-api-access.js
  src/libs/api-access/open-ai-api-standard-access.js
  src/libs/api-access/web-llm-access.js
  src/libs/conversation-management/conversations-management.js
  src/libs/state-management/watchers.js
  src/views/ChatLayout.vue
  vite.config.js
Labels: bug, enhancement

#129 Enhancement/mobile swipe improvements and high contrast messages option
  .firebase/hosting.ZGlzdA.cache
  .github/workflows/firebase-hosting-merge.yml
  CHANGELOG.md
  index.html
  package-lock.json
  package.json
  src/assets/tutorial.css
  src/components/ChatHeader.vue
  src/components/ContextWindow.vue
  src/components/ConversationsDialog.vue
  src/components/MessageItem.vue
  src/components/SettingsDialog.vue
  src/libs/conversation-management/useConversations.js
  src/libs/state-management/state.js
  src/libs/state-management/watchers.js
  src/libs/utils/general-utils.js
  src/libs/utils/settings-utils.js
  src/libs/utils/tutorial-utils.js
  src/views/ChatLayout.vue
Labels: enhancement, Usability

#131 Comprehensive Redesign and Enhancement of Settings Page
  .firebase/hosting.ZGlzdA.cache
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/components/ChatHeader.vue
  src/components/ContextWindow.vue
  src/components/ConversationsDialog.vue
  src/components/MessageItem.vue
  src/components/SettingsDialog.vue
  src/libs/api-access/claude-api-access.js
  src/libs/api-access/gpt-api-access.js
  src/libs/api-access/open-ai-api-standard-access.js
  src/libs/state-management/state.js
  src/libs/utils/constants.js
  src/libs/utils/general-utils.js
  src/libs/utils/tutorial-utils.js
  src/views/ChatLayout.vue
Labels: enhancement
